version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    # KLUCZOWE: Wymuszenie klasy 'medium', która jest dostępna w planie darmowym
      resource_class: medium
    steps:
      - checkout
      - run: make deps
      - run: make test
workflows:
  basic:
    jobs:
      - build-and-test
